api: "https://demo.ldproxy.net"
description: Validates the correct implementation of filters for the [Daraa API](https://demo.ldproxy.net/daraa) and [CShapes API](https://demo.ldproxy.net/cshapes).
protocol:
  plugin: "@catsjs/http"
  defaults:
    accept: "application/geo+json, application/problem+json;q=0.8"
contentTypes:
  - "@catsjs/json"
dslPlugins:
  - "plugins/filter"
verbose: false
report:
  dir: ../reports
  name: full
waitFor:
  path:
    - /daraa
    - /cshapes
  timeout: 120
